image: "rust:latest"

stages:
    - lint
    - test

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

lint:fmt:
    stage: lint
    before_script:
        - rustup component add rustfmt
    script: cargo fmt -- --check

lint:clippy:
    stage: lint
    before_script:
        - apt update -yqq
        - apt install -yqq --no-install-recommends clang libpq-dev
        - rustup component add clippy
    script: cargo clippy -- --deny warnings

.test: &test
    stage: test
    before_script:
        - MODE=$(echo "$CI_JOB_NAME" | cut -d ':' -f 2)
        - apt update -yqq
        - apt install -yqq --no-install-recommends clang graphviz libpq-dev
    script: make test MODE=$MODE

test:debug:
    <<: *test

test:release:
    <<: *test

cache:
    paths:
        - $CARGO_HOME
        - target/
